# -*- coding: utf-8 -*-

STOP_SHORT_NAMES = {
    300: 'מודיעין',  # Modiin,
    400: 'פאתי מודיעין',  # Modiin Center,
    700: 'קריית חיים',  # Kiryat Hayyim,
    800: 'קריית מוצקין',  # Kiryat Motzkin,
    1220: 'לב המפרץ',  # Leb Hmifratz,
    1300: 'חוצות המפרץ',  # Hutsot HaMifrats,
    1500: 'עכו',  # Akko,
    1600: 'נהריה',  # Nahariyya,
    2100: 'חיפה מרכז',  # Haifa Center HaShmona,
    2200: 'בת גלים',  # Haifa Bat Gallim,
    2300: 'חוף הכרמל',  # Haifa Hof HaKarmel (Razi'el),
    2500: 'עתלית',  # Atlit,
    2800: 'בנימינה',  # Binyamina,
    2820: 'קיסריה',  # Kesariyya - Pardes Hanna,
    3100: 'חדרה מערב',  # Hadera West,
    3300: 'נתניה',  # Natanya,
    3400: 'בית יהושע',  # Bet Yehoshua,
    3500: 'הרצליה',  # Herzliyya,
    3600: 'אוניברסיטה',  # Tel Aviv - University,
    3700: 'ת"א מרכז',  # Tel Aviv Center - Savidor,
    4100: 'בני ברק',  # Bne Brak,
    4170: 'קרית אריה',  # Petah Tikva   Kiryat Arye,
    4250: 'סגולה',  # Petah Tikva Sgulla,
    4600: 'ת"א השלום',  # Tel Aviv HaShalom,
    4640: 'צומת חולון',  # Holon Junction,
    4660: 'וולפסון',  # Holon - Wolfson,
    4680: 'יוספטל',  # Bat Yam - Yoseftal,
    4690: 'קוממיות',  # Bat Yam - Komemiyyut,
    4800: 'כפר חבד',  # Kfar Habbad,
    4900: 'ההגנה',  # Tel Aviv HaHagana,
    5000: 'לוד',  # Lod,
    5010: 'רמלה',  # Ramla,
    5150: 'גני אביב',  # Ganey Aviv,
    5200: 'רחובות',  # Rehovot E. Hadar,
    5300: 'באר יעקב',  # Be'er Ya'akov,
    5410: 'יבנה',  # Yavne,
    5800: 'אשדוד',  # Ashdod Ad Halom,
    5900: 'אשקלון',  # Ashkelon,
    6300: 'בית שמש',  # Bet Shemesh,
    6500: 'גן החיות',  # Jerusalem Biblical Zoo,
    6700: 'מלחה',  # Jerusalem Malha,
    7000: 'קרית גת',  # Kiryat Gat,
    7300: 'אוניברסיטה',  # Be'er Sheva North University,
    7320: 'ב"ש מרכז',  # Be'er Sheva Center,
    7500: 'דימונה',  # Dimona,
    8550: 'להבים',  # Lehavim - Rahat,
    8600: 'נתב"ג',  # Ben Gurion Airport,
    8700: 'כפר סבא',  # Kfar Sava,
    8800: 'ראש העין',  # Rosh Ha'Ayin North,
    9000: 'יבנה מערב',  # Yavne - West,
    9100: 'הראשונים',  # Rishon LeTsiyyon HaRishonim,
    9200: 'הוד השרון',  # Hod HaSharon,
    9600: 'שדרות',  # Sderot,
    9800: 'משה דיין',  # Rishon LeTsiyyon - Moshe Dayan,
}


