#!/usr/bin/env python
import os
import sys
dir=os.path.dirname(os.path.dirname(__file__))
sys.path.append(dir)
os.environ['DJANGO_SETTINGS_MODULE']='opentrain.settings'
import sys
import timetable.services

trip = timetable.services.get_trip(sys.argv[1])
print('')
trip.print_stoptimes()
print('')
