#!/usr/bin/env python
import os
import sys
sys.path.append(os.getcwd())
sys.path.append(os.path.dirname(os.getcwd()))
dir=os.path.dirname(os.path.dirname(__file__))
sys.path.append(dir)
os.environ['DJANGO_SETTINGS_MODULE']='opentrain.settings'
import sys
import timetable.services

trip = timetable.services.get_trip(sys.argv[1])
print('')
trip.print_stoptimes()
print('')
